### ISSUE TITLE
Whitelist does not work if user is already banned

### ISSUE THREAD

**Issue by SteelManITA** [Squirrel-Network/nebula8#18]
If the user was banned by the bot, and I use /w in response, the user is added to whitelist successfully, but it's still banned

**Comment by BluLupo** [comment]
@SteelManITA The whitelist doesn't have that function. The whitelist only works in relation to the blacklist not all bot functions.

**Comment by SteelManITA** [comment]
Yes, but if I add user to the whitelist, I want to remove him from the blacklist, and nebula doesn't

**Comment by BluLupo** [comment]
ok the problem will be corrected
