### ISSUE TITLE
Upgrade from python telegram bot 13.5 to 13.7

### ISSUE THREAD

**Issue by BluLupo** [Squirrel-Network/nebula8#23]
https://python-telegram-bot.readthedocs.io/en/stable/changelog.html#version-13-7

Reference: https://github.com/Squirrel-Network/nebula8/blob/7856a9212de0c4c75cc3535bf45f9b50ee8575d8/requirements.txt#L19

**Comment by TheLonelyAdventurer** [comment]
https://github.com/Squirrel-Network/nebula8/blob/master/core/commands/admin/ban.py#L53-L62
