### ISSUE TITLE
Warning message

### ISSUE THREAD

**Issue by node-red-italia** [Squirrel-Network/nebula8#34]
Hi Nebula staff, when I use the warning command to a user it is not clear if the user is warned, how many warnings he has and the maximum number of warnings set in a group.

Another thing, nebula replies with a text message containing the user Id, many Telegram users don't even know what it is. If possible I would use the username, so the user also remains tagged and knows he has received a warning.

Thanks
A greeting

**Comment by BluLupo** [comment]
Hello @node-red-italia  the warnings in the group as well as other data you can find them by doing the command /status, as for the warnings of the warn we are providing to improve them

**Comment by BluLupo** [comment]
Fixed in Release 8.6.2 https://github.com/Squirrel-Network/nebula8/commit/3553b9b18a8088fabfd6bce826b825a7cabc3d0a
