### ISSUE TITLE
Make the bot compatible with topics

### ISSUE THREAD

**Issue by BluLupo** [Squirrel-Network/nebula8#37]

**Comment by BluLupo** [comment]
Fix by Lib => https://github.com/python-telegram-bot/python-telegram-bot/issues/3340

**Comment by Poolitzer** [comment]
Hi, just saw the mention here. If you reply to messages, you can already make it "compatible" for reading/writing to chats. No management of topic ofc.

**Comment by BluLupo** [comment]
We were trying different solutions but I saw that you are already working on an update, we use this method for messages (which works as an alias) https://github.com/Squirrel-Network/nebula8/blob/master/core/utilities /message.py#L13 I should modify that function do the update

**Comment by BluLupo** [comment]
Fix in this commit https://github.com/Squirrel-Network/nebula8/commit/1b46bcf538bec6d9cebc6fbfcee81edf3deea354
