### ISSUE TITLE
Make the project compatible and usable with poetry

### ISSUE THREAD

**Issue by BluLupo** [Squirrel-Network/nebula8#4]
Info=> https://python-poetry.org/

**Comment by tanya4067** [comment]
Hey I'd like to contribute

**Comment by BluLupo** [comment]
@tanya4067 We would love to help, you can make a pull request, our contacts can be found on @squirrelnetwork

**Comment by tanya4067** [comment]
Thank you for your response

**Comment by BluLupo** [comment]
@tanya4067 how is it going?
